# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_accueil:
    path:      /{page}
    defaults:
        _controller: OCPlatformBundle:Platform:index
        page: 1
    requirements:
        page: \d*

oc_platform_voir:
    path:      /annonce/{id_annonce}
    defaults:
        _controller: OCPlatformBundle:Annonce:voir
    requirements:
        id_annonce: \d+

oc_platform_ajouter:
    path:      /ajouter
    defaults: { _controller: OCPlatformBundle:Annonce:ajouter }

oc_platform_editer:
    path:      /editer/{id_annonce}
    defaults:
        _controller: OCPlatformBundle:Annonce:editer
    requirements:
        id_annonce: \d+

oc_platform_supprimer:
    path:      /supprimer/{id_annonce}
    defaults:
        _controller: OCPlatformBundle:Annonce:supprimer
    requirements:
        id_annonce: \d+