services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Services\Antispam
        arguments:
        - "@mailer"
        - '%locale'
        - 50
    annonces:
        class: OC\PlatformBundle\Services\Annonces