<?php

namespace OC\PlatformBundle\Repository;

/**
 * AnnonceNiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceNiveauRepository extends \Doctrine\ORM\EntityRepository
{
}
