<?php

namespace OC\PlatformBundle\Repository;

/**
 * AnnonceCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
