<?php

namespace OC\PlatformBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAnnonceWithCategories(array $nomCategories)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->innerJoin('a.categories', 'cat')
            ->addSelect('cat');

        $qb->where($qb->expr()->in('cat.nom', $nomCategories));

        return $qb->getQuery()->getResult();
    }

    public function getLastAnnonces($limit)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

}
